name: sql_client
description: "Client Application"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_animate: ^4.5.0
  fluttertoast: ^8.2.4
  icons_plus: ^5.0.0
  animated_loading_border: ^0.0.2
  google_fonts: ^6.1.0
  flutter_animated_button: ^2.0.3
  crypto: ^3.0.3
  data_table_2: ^2.5.11
  date_format: ^2.0.7
  table_calendar: ^3.1.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
